;;; Package namespace convenience module for Gaurix.
(define-module (gaurix packages)
  #:use-module (gaurix packages hello-gaurix)
  #:use-module (gaurix packages localsend-bin)
  #:use-module (gaurix packages aider-chat)
  #:use-module (gaurix packages lmstudio-bin)
  #:use-module (gaurix packages llama-cpp-cuda)
  #:use-module (gaurix packages visual-studio-code-bin)
  #:use-module (gaurix packages sunshine)
  #:use-module (gaurix packages sunshine-bin)
  #:use-module (gaurix packages fluxer-bin)
  #:use-module (gaurix packages comfyui-cuda)
  #:use-module (gaurix packages general-compat)
  #:use-module (gaurix packages ffglitch)
  #:use-module (gaurix packages python-compat)
  #:export (hello-gaurix
            localsend-bin
            aider-chat
            lmstudio-bin
            llama-cpp-cuda
            visual-studio-code-bin
            sunshine
            sunshine-bin
            fluxer-bin
            comfyui-cuda
            gtk2
            gnu-netcat
            qt5-webengine
            python312
            openssl-1.1
            yt-dlp-git
            ripgrep-git
            fd-git
            eza-git
            zoxide-git
            shellcheck-bin
            xlibre-xserver
            xlibre-xserver-bootstrap
            xlibre-xserver-common
            xlibre-xserver-devel
            xlibre-xserver-xephyr
            xlibre-xserver-xnest
            xlibre-xserver-xvfb
            qt5-remoteobjects
            qt5-webchannel
            qt5-websockets
            dashbinsh
            libidn11
            ncurses5-compat-libs
            neovim-symlinks
            neovim-git
            lib32-libidn11
            gtk-engine-murrine
            gtkspell
            python313
            lib32-gtk2
            openssl-1.0
            botan2
            piper-tts
            libjpeg6-turbo
            ffglitch
            quickshell-git
            openscad-git
            mesa-git
            openrgb-git
            hashcat-git
            mold-git
            picom-git
            papirus-icon-theme-git
            libplasma-git
            qutebrowser-git
            cataclysm-dda-git
            mecab-git
            openttd-jgrpp-git
            dragon-drop-git
            python-protobuf-git
            protobuf-git
            libarchive-git
            dstask-git
            fsearch-git
            procs-git
            llama.cpp-vulkan
            lib32-openssl-1.0
            zfs-dkms
            python-valkey-git
            calibre-bin
            pandoc-bin
            beads-bin
            blender-bin
            musescore-bin
            docker-compose-bin
            pnmixer-bin
            xremap-x11-bin
            cura-bin
            zig-bin
            solidity-bin
            openshot-bin
            sd-git
            snitch-bin
            meshlab-bin
            cava-git
            onedrive-abraunegg
            i2p
            fluxer-git
            arc-solid-gtk-theme
            arc-gtk-theme
            libindicator-gtk2
            libdbusmenu-gtk2
            lib32-libjpeg6-turbo
            lib32-openssl-1.1
            librsvg-noglycin-docs
            librsvg-noglycin
            qt6-avif-image-plugin
            woff2-space-grotesk
            woff-space-grotesk
            qt5-avif-image-plugin
            otf-space-grotesk
            freerdp2
            icoextract
            lib32-libpng12
            libvpx1.3
            libtiff4
            librtmp0
            libgcrypt15
            lib32-libvpx1.3
            lib32-libtiff4
            lib32-librtmp0
            lib32-libgcrypt15
            lib32-glew1.10
            glew1.10
            lib32-libdbusmenu-gtk2
            zfs-utils
            lib32-libappindicator-gtk2
            python311
            youtube-dl
            python310
            gcc14-libs
            gcc14-fortran
            gcc14
            freetype2-woled
            bird2
            lib32-libindicator-gtk2
            blesh-git
            dualsensectl-git
            qt6ct-kde
            ffmpeg-full
            openrdap-client
            rclone-browser
            kwin-effects-geometry-change
            kwin-effect-rounded-corners-git
            evolution-tray-git
            piper-voices-en-us
            libadwaita-without-adwaita
            pulseaudio-ctl
            ares-emu
            libwacom-surface
            xpadneo-dkms-git
            pidgin-mini
            kwin-effects-glass-git
            gtkmm-docs
            breeze-plus
            blender-benchmark
            ibus-bamboo
            librewolf-allow-dark
            gimp-devel
            alacritty-themes
            josm-latest
            gforth-docs
            python-pdm-pep517
            python-argparse-from-file
            python-ewmh
            python-transmission-rpc
            python-proton-client
            trezor-udev
            xlibre-input-libinput
            torchvision-rocm
            python-torchvision-rocm
            adw-gtk-theme-git
            qt5-charts
            perl-file-rename))
